dataset_info:
  target_column: "Toxicity"
  drop_columns:
    - "Viability (%)"
    - "Method core size"
    - "Method hydro size"
    - "Method surface charge"
    - "Method surface area"
    - "Assay"
    - "Cell name"
    - "Cell species"


columns:

  "Material type":
    type: object
    nullable: False
  "Exposure dose (ug/mL)":
    type: float
    nullable: False
  "Exposure time":
    type: object
    nullable: False


  "Core size (nm)":
    type: float
    nullable: False
  "Hydro size (nm)":
    type: float
    nullable: False
  "Surface charge (mV)":
    type: float
    nullable: False
  "Surface area (m2/g)":
    type: float
    nullable: False
  "_Hsf (eV)":
    type: float
    nullable: False
  "Ec (eV)":
    type: float
    nullable: False
  "Ev (eV)":
    type: float
    nullable: False
  "_MeO (eV)":
    type: float
    nullable: False


  "Toxicity":
    type: object
    nullable: False


  "Viability (%)":
    type: float
    nullable: True
  "Method core size":
    type: object
    nullable: True
  "Method hydro size":
    type: object
    nullable: True
  "Method surface charge":
    type: object
    nullable: True
  "Method surface area":
    type: object
    nullable: True
  "Assay":
    type: object
    nullable: True
  "Cell name":
    type: object
    nullable: True
  "Cell species":
    type: object
    nullable: True


numerical_columns:
  - "Core size (nm)"
  - "Hydro size (nm)"
  - "Surface charge (mV)"
  - "Surface area (m2/g)"
  - "_Hsf (eV)"
  - "Ec (eV)"
  - "Ev (eV)"
  - "_MeO (eV)"
  - "Exposure dose (ug/mL)"

categorical_columns:
  - "Material type"

